version: '3.8'
services:
  traefik:
    image: traefik:v3.3
    deploy:
      placement:
        constraints:
          - node.role == manager
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - OVH_ENDPOINT=${OVH_ENDPOINT}
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
    volumes:
      - etc_traefik:/etc/traefik/
      - traefik:/traefik-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - traefik-net
  crawler:
    image: satcomx00/python-crawler:latest
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
    environment:
      - REDIS_URL=redis://redis-master:6379
      - REDIS_HOST=redis-slave
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_RETRY_COUNT=3
      - REDIS_RETRY_DELAY=1
    depends_on:
      - redis-master
    networks:
      - traefik-net
      - redis-net
    labels:
      - "traefik.enable=true"
  redis-master:
    image: redis:latest
    command: >
      redis-server 
      --port 6379
      --requirepass ${REDIS_PASSWORD:-redispassword}
      --masterauth ${REDIS_PASSWORD:-redispassword}
    networks:
      - redis-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - redis-master-data:/data
  redis-slave:
    image: redis:latest
    command: >
      redis-server
      --port 6379
      --slaveof redis-master 6379
      --requirepass ${REDIS_PASSWORD:-redispassword}
      --masterauth ${REDIS_PASSWORD:-redispassword}
    networks:
      - redis-net
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    volumes:
      - redis-slave-data:/data
networks:
  traefik-net:
    driver: overlay
  redis-net:
    driver: overlay
volumes:
  etc_traefik:
  traefik:
  letsencrypt:
  redis-master-data:
  redis-slave-data: